from config import CURRENT_LOCALIZATION

# Локализации
localizations = {
    "ru": {
        # Theme
        "dark": "Тёмная",
        "white": "Светлая",
        "red": "Красная",
        "blue": "Синяя",
        "green": "Зелёная",
        "contrast": "Контрастная",
        "gray": "Серая",
        "orange": "Оранжевая",
        "themes": "Темы",
        "topmost": "Поверх всех окон",
        "on2": "вкл",
        "off2": "выкл",
        "help": "Помощь",
        "view": "Вид",
        "show_date": "Показывать только задачи с датой",
        "FE": "Редактор Файлов",
        "font": "Шрифт",
        "line": "Строка",
        "column": "Колонка",
        # OF
        "unknown_error": "Неизвестная ошибка",
        "open_file_error": "Не удалось открыть файл",
        # FE
        "open": "Открыть",
        "file": "Файл",
        "save": "Сохранить",
        "save_as": "Сохранить как",
        "exit": "Выход",
        "editing": "Редактирование",
        "cancel": "Отменить",
        "repeat": "Повторить",
        "cut": "Вырезать",
        "copy": "Копировать",
        "paste": "Вставить",
        "select_all": "Выделить всё",
        "font_size": "Размер шрифта",
        "new_file": "Новый файл",
        "text_file": "Текстовые файлы",
        "all_files": "Все файлы",
        "file_not_found": "Файл не найден",
        "success_saved": "успешно сохранён",
        "save_changes?": "У вас есть несохранённые изменения. Сохранить файл перед выходом?",
        "match_case": "Учитывать регистр",
        "whole_words": "Слова Целиком",
        "back": "Назад",
        "next": "Далее",
        "fe_critical_error": "В Компоненте FileEditor произошла неизвестная ошибка!",
        "cuttlefish": "Сепия",
        "load_file": "при загрузке файла",
        "save_file": "при сохранении файла",
        "save_file2": "Сохранить файл?",
        "select_file": "Выберите файл",
        "encrypt_file": "Зашифровать файл?",
        "enter_clyth": "Введите ключ шифрования: ",
        "decrypt_file": "Расшифровать файл?",
    },
    "en": {
        # Theme
        "dark": "Dark",
        "white": "Light",
        "red": "Red",
        "blue": "Blue",
        "green": "Green",
        "contrast": "Contrast",
        "gray": "Gray",
        "orange": "Orange",
        "themes": "Themes",
        "topmost": "On top of all windows",
        "on2": "on",
        "off2": "off",
        "help": "Help",
        "view": "View",
        "show_date": "Show only tasks with a date",
        "FE": "File Editor",
        "font": "Font",
        "line": "Line",
        "column": "Column",
        # OF
        "unknown_error": "Unknown error",
        "open_file_error": "Failed to open file",
        # FE
        "file": "File",
        "save": "Save",
        "save_as": "Save as",
        "exit": "Exit",
        "editing": "Editing",
        "cancel": "Cancel",
        "repeat": "Repeat",
        "cut": "Cut",
        "copy": "Copy",
        "paste": "Paste",
        "select_all": "Select all",
        "font_size": "Font size",
        "new_file": "New file",
        "text_file": "Text files",
        "all_files": "All files",
        "file_not_found": "File not found",
        "success_saved": "Successfully saved",
        "save_changes?": "You have unsaved changes. Save the file before exiting?",
        "match_case": "Match case",
        "whole_words": "Whole words",
        "back": "Previous",
        "next": "Next",
        "fe_critical_error": "In Component FileEditor encountered an unknown error!",
        "cuttlefish": "Sepia",
        "crowbar_scripts": "Mount Antivirus Scripts",
        "load_file": "while loading a file",
        "save_file": "while saving a file",
        "save_file2": "Save file?",
        "select_file": "Select a file",
    },
    "ua": {
        # Theme
        "Dark": "Темна",
        "white": "Світла",
        "red": "Червона",
        "blue": "Синя",
        "green": "Зелена",
        "contrast": "Контрастна",
        "gray": "Сірий",
        "orange": "Помаранчева",
        "themes": "Теми",
        "topmost": "Поверх усіх вікон",
        "on2": "вкл",
        "off2": "викл",
        "help": "Допомога",
        "view": "Вигляд",
        "show_date": "Показувати лише завдання з датою",
        "FE": "Редактор Файлів",
        "font": "Шрифт",
        "line": "Рядок",
        "column": "Колонка",
        #OF
        "unknown_error": "Невідома помилка",
        "open_file_error": "Не вдалося відкрити файл",
        # FE
        "file": "Файл",
        "save": "Зберегти",
        "save_as": "Зберегти як",
        "exit": "Вихід",
        "editing": "Редагування",
        "cancel": "Скасувати",
        "repeat": "Повторити",
        "cut": "Вирізати",
        "copy": "Копіювати",
        "paste": "Вставити",
        "select_all": "Виділити все",
        "font_size": "Розмір шрифту",
        "new_file": "Новий файл",
        "text_file": "Текстові файли",
        "all_files": "Всі файли",
        "file_not_found": "Файл не знайдено",
        "success_saved": "успішно збережено",
        "save_changes?": "У вас є незбережені зміни. Зберегти файл перед виходом?",
        "match_case": "Враховувати регістр",
        "whole_words": "Слова цілком",
        "back": "Назад",
        "next": "Далі",
        "fe_critical_error": "У Компоненті FileEditor сталася невідома помилка!",
        "cuttlefish": "Сепія",
        "crowbar_scripts": "Скрипти Антивірусу Монтування",
        "load_file": "при завантаженні файлу",
        "save_file": "при збереженні файлу",
        "save_file2": "Зберегти файл?",
        "select_file": "Виберіть файл",
    },
}

# Возвращаем нужный текст или сам ключ если нужного текста нет в текущем языке
def l(key, language=CURRENT_LOCALIZATION):
    """
    Функция для получения текста из локализации
    key - имя ключа текста/реплики/диалога
    language - Язык на котором вернуть текст
    return - функция возвращает текст из локализации, если такого ключа в указанной локализации нет то будет возвращён сам ключ
    """
    return localizations.get(language, {}).get(key) or key
